/* Auto-generated by tools/decomp/gen_lift_main.py — do not edit. */
/* Regenerate: make lift-main */
#ifndef LIFT_SYMS_H
#define LIFT_SYMS_H

#include "i960_lift.h"

/* Direct C calls for lifted ROM symbols (prefer over i960_call_rom). */
extern void attract_credit_hud_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f5f0 */
extern void attract_credit_hud_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f4d0 */
extern u32 attract_credit_query(u32 chute_index, u32 arg1, u32 arg2); /* @rom 0x0000be68 */
extern u32 attract_credit_spend(u32 chute_index, u32 arg1, u32 arg2); /* @rom 0x0000bea0 */
extern void attract_credit_stamp_empty(u32 slot, u32 arg1, u32 arg2); /* @rom 0x0000bee0 */
extern void attract_credit_stamp_paid(u32 slot, u32 arg1, u32 arg2); /* @rom 0x0000bfa0 */
extern void attract_hud_setup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001b940 */
extern void attract_logo_cgm_scale_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00032720 */
extern void attract_logo_cgm_submit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00032790 */
extern void attract_logo_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00032f70 */
extern void attract_logo_tile_stripe(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000326c8 */
extern void attract_mode3_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001b8c0 */
extern void attract_scene_slot_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c0e0 */
extern void backup_sram_sync(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00008f28 */
extern void boot_attract_flags_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00003260 */
extern void boot_copyright_notice_show(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001a990 */
extern void boot_entry(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00000310 */
extern void boot_io_glyph_finish(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001e80 */
extern void boot_io_glyph_stream(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001e20 */
extern void boot_io_ready_wait(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001dd8 */
extern void boot_io_xmit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001db8 */
extern void boot_palette_splash_upload(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026758 */
extern void boot_tile_blit_chain(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026800 */
extern void boot_tile_blit_register(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026860 */
extern void boot_tile_map_fill(u32 x, u32 y, u32 width, u32 height); /* @rom 0x00027260 */
extern void boot_tile_map_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026a10 */
extern void boot_tile_opcode_dispatch(u32 opcode_word); /* @rom 0x00027008 */
extern void boot_tile_script_blank_n(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00027160 */
extern void boot_tile_script_format(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000271d8 */
extern void boot_tile_script_gate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00029100 */
extern void boot_tile_script_run(u32 script_ptr); /* @rom 0x00027130 */
extern void boot_tile_scroll_copy(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000268b0 */
extern void boot_tile_splash_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026980 */
extern void boot_tile_splash_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026690 */
extern u32 catalog_draw_setup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00029eb0 */
extern void cgm_1111_flush(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a120 */
extern u32 cgm_digit_staging(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a2e0 */
extern u32 cgm_fifo_upload_runner(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a5a0 */
extern void cgm_fifo_upload_span(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a750 */
extern void cgm_fifo_upload_wrapper(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a6d0 */
extern void cgm_leading_colorbase(void * arg0, void * arg1, u32 arg2); /* @rom 0x0002a050 */
extern void cgm_palette_scratch_write(u32 pen, u32 color15); /* @rom 0x0002a490 */
extern void cgm_printf_handler_d(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0005d3dc */
extern void cgm_printf_handler_digit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0005d304 */
extern void cgm_printf_handler_hash(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0005d1c8 */
extern void cgm_printf_handler_u(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0005d714 */
extern void cgm_record_dispatch(u32 arg0, u32 arg1); /* @rom 0x0002a0f8 */
extern void cgm_record_prepare_batch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a290 */
extern void cgm_scratch_pool_alloc_link(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002aa90 */
extern void cgm_scratch_pool_reset(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a7a0 */
extern void cgm_template_emit(u32 tpl_vaddr, u32 g6, u32 r9_flags, u32 r14_repeat); /* @rom 0x0005d7e8 */
extern u32 cgm_thunk_walk(u32 arg0, u32 arg1); /* @rom 0x00029958 */
extern void coin_option_defaults(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000a940 */
extern u32 coin_option_validate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000a7a0 */
extern void comm_attract_bal_trampoline(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00016b28 */
extern void comm_attract_board_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000fa00 */
extern void comm_attract_board_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f6d0 */
extern u32 comm_attract_board_tick(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00016540 */
extern void comm_attract_carousel_advance(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000fdc8 */
extern void comm_attract_catalog_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003de18 */
extern void comm_attract_countdown_tick(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f9d0 */
extern void *comm_attract_course_chain_prep(void * arg0, u32 arg1); /* @rom 0x0003f1b8 */
extern void comm_attract_course_chain_restore(u32 arg0, u32 arg1); /* @rom 0x0003f1f8 */
extern u32 comm_attract_course_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003f2f0 */
extern void comm_attract_course_record_copy(void *arg0, u32 arg1, u32 arg2); /* @rom 0x0003f220 */
extern void comm_attract_geo_script_finish(void * arg0, void * arg1, u32 arg2); /* @rom 0x00011b90 */
extern void comm_attract_hud_copyright_stamps(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00012c70 */
extern void comm_attract_hud_post_rank(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000134a0 */
extern void comm_attract_hud_scroll_fill(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00013238 */
extern void comm_attract_hud_scroll_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00013340 */
extern void comm_attract_inner_0(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f840 */
extern void comm_attract_inner_1(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f970 */
extern void comm_attract_inner_2(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00010710 */
extern void comm_attract_inner_3(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00010940 */
extern void comm_attract_inner_4(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00010e30 */
extern void comm_attract_inner_5(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00011040 */
extern void comm_attract_inner_6(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000113a0 */
extern void comm_attract_inner_7(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000115a0 */
extern void comm_attract_inner_8(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f7d0 */
extern void comm_attract_inner_9(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00013810 */
extern void comm_attract_phase_setup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000137d0 */
extern void comm_attract_reset(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026228 */
extern void comm_attract_scene_alloc(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00012b70 */
extern void comm_attract_scene_hud(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00012cc0 */
extern void comm_attract_scene_hud_alt(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00012d90 */
extern u32 comm_attract_script_frame_setup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000104a0 */
extern void comm_attract_script_glyph_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00010310 */
extern u32 comm_attract_slot_scan(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000fe40 */
extern void comm_attract_splash_bind(u32 script_index); /* @rom 0x0000f670 */
extern void comm_attract_threshold_tile_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f620 */
extern void comm_board_absent_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001bd0 */
extern void comm_board_absent_xfer(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001cb8 */
extern void comm_board_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000ccb0 */
extern void comm_board_idle_gate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002220 */
extern void comm_board_present_glyph_loop(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000021c0 */
extern void comm_board_present_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001c50 */
extern void comm_board_probe(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001c60 */
extern void comm_board_setup_probe(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000cdf8 */
extern void comm_bx_return_g0(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001a58 */
extern void comm_bx_return_g1(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001d38 */
extern void comm_draw_setup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026150 */
extern void comm_flag_gate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002200 */
extern void comm_io_glyph_slot(u32 slot_index, u32 glyph_word, u32 arg2); /* @rom 0x00002080 */
extern void comm_palette_index_call(u32 slot_index); /* @rom 0x00026140 */
extern void comm_present_io_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002180 */
extern void comm_scene_catalog_init(u32 mode, u32 arg1, u32 arg2); /* @rom 0x0000c060 */
extern void copro_bootstrap_entry(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004d50 */
extern void copro_fifo_init(u32 arg0, u32 arg1); /* @rom 0x00004ca8 */
extern void copy_catalog_index_table(void * arg0, u32 arg1, u32 arg2); /* @rom 0x000282d0 */
extern u32 draw_scene_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00029c10 */
extern u32 erase_scene_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00029d60 */
extern void format_scan_bx_stub(u32 arg0, u32 arg1); /* @rom 0x0005cd38 */
extern void game_coin_chute_scan(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000ac30 */
extern void game_coin_chute_slot(u32 chute, u32 arg1, u32 arg2); /* @rom 0x0000ab10 */
extern void game_coin_credit_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000ac50 */
extern void game_coin_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000af00 */
extern void game_coin_option_boot(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002a20 */
extern void game_coin_service_edge(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000ae28 */
extern void game_coin_sram_reset(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000a9d0 */
extern void game_cold_boot_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000032a0 */
extern u32 game_comm_aa24_seed(u32 arg0, u32 arg1); /* @rom 0x0001a7b8 */
extern void game_d6_count_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00031768 */
extern void game_d6_mode_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000316c8 */
extern void game_d6_tracker_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000323a0 */
extern void game_dispatch_main(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00003150 */
extern void game_frame_update(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00022b60 */
extern void game_inner_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001aa30 */
extern void game_inner_flags_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000f818 */
extern void game_io_coin_sense(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002240 */
extern void game_io_poll(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000024c0 */
extern u32 game_irq_wr_stub(u32 arg0, u32 arg1); /* @rom 0x00001758 */
extern void game_mmio_boot_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001788 */
extern void game_mode_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00003650 */
extern void game_mode_index_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002930 */
extern u32 game_mode_table_fetch(u32 table_ptr, u32 row_count); /* @rom 0x000297e0 */
extern void game_option_flags_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002970 */
extern void game_seed_globals(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000036b0 */
extern void game_staging_bx(u32 arg0, u32 arg1); /* @rom 0x00033e18 */
extern void game_staging_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00032fa0 */
extern void game_start_car_display(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00014d60 */
extern void game_start_car_select(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00015200 */
extern void game_start_car_select_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00014820 */
extern void game_start_catalog_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000144f0 */
extern void game_start_champ_enter(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c090 */
extern void game_start_course_display(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00015fd0 */
extern void game_start_course_select(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000162e0 */
extern void game_start_course_select_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00015380 */
extern void game_start_display_setup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00014160 */
extern void game_start_flags_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001abb0 */
extern void game_start_mode_select(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00014440 */
extern void game_start_mode_select_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00013ce0 */
extern void game_start_phase_0(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001b4d0 */
extern void game_start_practice_enter(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c140 */
extern void game_start_practice_slot_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c1a0 */
extern void game_start_race_aea8_set(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c808 */
extern void game_start_race_cam_bind(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00020310 */
extern void game_start_race_cam_boot(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001f0d0 */
extern void game_start_race_cam_chase(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001fdc0 */
extern void game_start_race_cam_chase_alt(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001ff60 */
extern void game_start_race_cam_desert(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001fa20 */
extern void game_start_race_cam_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000206e0 */
extern void game_start_race_cam_matrix(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00020390 */
extern void game_start_race_cam_matrix_long(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000203d0 */
extern void game_start_race_cam_object_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00034140 */
extern void game_start_race_cam_pose_table(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00021cd8 */
extern void game_start_race_cam_rebind(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000202e0 */
extern void game_start_race_cam_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001f1d0 */
extern void game_start_race_cgm_batch_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001dad0 */
extern void game_start_race_cgm_colorbase_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00040790 */
extern void game_start_race_cgm_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001dd30 */
extern void game_start_race_countdown_prg(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000211f0 */
extern void game_start_race_course_centroid(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00041e70 */
extern void game_start_race_course_obj_draw_21(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002bb50 */
extern void game_start_race_course_obj_draw_4(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002b420 */
extern void game_start_race_course_obj_init_21(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002bb80 */
extern void game_start_race_course_obj_init_4(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002b580 */
extern u32 game_start_race_desert_near_pick(u32 query, u32 idx, u32 arg2); /* @rom 0x00041f80 */
extern void game_start_race_desert_node_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000427a0 */
extern void game_start_race_desert_node_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00043790 */
extern void game_start_race_desert_obj_near_flag(u32 node, u32 arg1, u32 arg2); /* @rom 0x00042190 */
extern void game_start_race_desert_pose_step(u32 node, u32 arg1, u32 arg2); /* @rom 0x000422b0 */
extern void game_start_race_desert_rng_jitter(u32 xyz, u32 scale_in, u32 arg2); /* @rom 0x00041be0 */
extern u32 game_start_race_desert_slot_flag(u32 pos, u32 angles, u32 lane); /* @rom 0x00046470 */
extern u32 game_start_race_desert_table_pick(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00041b78 */
extern void game_start_race_desert_tgp55_walk(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00041ca0 */
extern void game_start_race_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001bba0 */
extern void game_start_race_gate_bind(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00022768 */
extern void game_start_race_gate_walk(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000227b0 */
extern void game_start_race_geo_prg_hud_go(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00021340 */
extern void game_start_race_geo_prg_slot(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00021370 */
extern void game_start_race_geo_prg_thunk(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00021330 */
extern void game_start_race_hud_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00020740 */
extern void game_start_race_hud_lap_time(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001e610 */
extern void game_start_race_hud_layers(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001e1d0 */
extern void game_start_race_hud_position(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001ecc0 */
extern void game_start_race_hud_progress(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001edb0 */
extern void game_start_race_hud_row_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001e498 */
extern void game_start_race_hud_speed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001df40 */
extern void game_start_race_hud_string_draw(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001dc00 */
extern void game_start_race_hud_tach(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001e500 */
extern void game_start_race_lap_bank_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c830 */
extern void game_start_race_lap_bank_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00018248 */
extern void game_start_race_lap_tick(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c8b8 */
extern void game_start_race_list_flag_prep(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c2a0 */
extern void game_start_race_list_free_a(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a928 */
extern void game_start_race_list_free_b(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a968 */
extern u32 game_start_race_list_head_fetch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002ab48 */
extern void game_start_race_list_unlink(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002aaf0 */
extern void game_start_race_list_walk(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002ab80 */
extern void game_start_race_logo_extra(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000420f0 */
extern void game_start_race_obj_bind(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00023110 */
extern void game_start_race_obj_car_attach(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002c850 */
extern u32 game_start_race_obj_car_contact_solve(u32 arg0, void *arg1, void *arg2); /* @rom 0x0002f8a0 */
extern void game_start_race_obj_car_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002bcf0 */
extern void game_start_race_obj_car_integrate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002cce0 */
extern void game_start_race_obj_car_motion(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000304f0 */
extern void game_start_race_obj_car_peer(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002cc78 */
extern void game_start_race_obj_car_velocity_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00030e00 */
extern void game_start_race_obj_car_yaw_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002f3c0 */
extern void game_start_race_obj_depth_pass(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00023280 */
extern void game_start_race_obj_list(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00022e20 */
extern void game_start_race_obj_pose_publish(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002bc08 */
extern void game_start_race_obj_publish(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00022c70 */
extern void game_start_race_obj_road_angles(void *arg0, u32 arg1, u32 arg2); /* @rom 0x0002f520 */
extern void game_start_race_obj_road_attach(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002c8d0 */
extern void game_start_race_obj_road_span(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000311e0 */
extern void game_start_race_obj_road_span_basis(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00031320 */
extern void game_start_race_obj_scan(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00022940 */
extern void game_start_race_obj_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000219c0 */
extern void game_start_race_obj_seed_cars(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000217e0 */
extern void game_start_race_obj_seed_practice(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00021918 */
extern void game_start_race_obj_sort_index(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000231f0 */
extern void game_start_race_obj_span_test(u32 self_z, void *self_xyz, u32 other_z); /* @rom 0x00022850 */
extern void game_start_race_object_pen_desc(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000248b0 */
extern void game_start_race_object_pen_far(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00024560 */
extern void game_start_race_object_pen_mid(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000240c0 */
extern void game_start_race_object_pen_walk(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00024c50 */
extern void game_start_race_pose_ring_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00046160 */
extern void game_start_race_prg_budget(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c450 */
extern void game_start_race_rank_list_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00047330 */
extern void game_start_race_slot0(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001ca70 */
extern void game_start_race_slot1(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001cd20 */
extern void game_start_race_slot2(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001ce30 */
extern void game_start_race_slot3(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001d160 */
extern void game_start_race_sub_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001ca30 */
extern void game_start_race_sub_reset(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001c9c0 */
extern void game_start_race_timer_arm(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0001bf50 */
extern u32 game_start_select_confirm(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00015030 */
extern void game_start_select_icons(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00014530 */
extern void game_start_select_timer_arm(void); /* @rom 0x00014678 */
extern u32 game_start_select_timer_gate(void); /* @rom 0x000146a8 */
extern void game_subsys_boot(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002c80 */
extern void game_subsys_init_stub(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00031650 */
extern u32 game_workram_bx_stub(u32 arg0, u32 arg1); /* @rom 0x0003f4b8 */
extern void geo_attract_copro_marker_burst(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00032410 */
extern u32 geo_attract_copro_object(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00032150 */
extern void geo_attract_copro_submit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00031fc0 */
extern void geo_attract_copro_vec_scale(u32 arg0, void * arg1, void * arg2); /* @rom 0x00011a80 */
extern u32 geo_attract_course_carousel_draw(u32 arg0, void * arg1, u32 arg2); /* @rom 0x0003bcc0 */
extern void geo_attract_course_catalog_span(u32 rec_va, u32 span_a, u32 span_b); /* @rom 0x0003b7c0 */
extern void geo_attract_course_prg_mode(u32 course_ix, u32 span_a, u32 arg2); /* @rom 0x0003b9b0 */
extern void geo_attract_course_slot_call(void * arg0, void * arg1, u32 arg2); /* @rom 0x0003b200 */
extern void geo_attract_course_view_bind(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003be30 */
extern void geo_attract_fp_series(u32 table_va, u32 arg1, u32 arg2); /* @rom 0x00033c00 */
extern void geo_attract_glyph_emit(void * arg0, void * arg1, u32 arg2); /* @rom 0x00023a80 */
extern void geo_attract_object_extra(void * arg0, u32 arg1, u32 arg2); /* @rom 0x000317b0 */
extern void geo_attract_object_pen(void * arg0, u32 arg1, u32 arg2); /* @rom 0x000247d0 */
extern u32 geo_attract_pen_angle_push(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003ed20 */
extern void geo_attract_pen_prg_push_a(u32 pen_mode, u32 arg1, u32 arg2); /* @rom 0x0003ef70 */
extern void geo_attract_pen_prg_push_b(uintptr_t obj, uintptr_t obj18, u32 wr_base); /* @rom 0x0003ef10 */
extern void geo_attract_record_index(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003f410 */
extern void geo_attract_span_table_draw(u32 table_ix, u32 span_b, u32 list_len); /* @rom 0x00047920 */
extern void geo_countdown_keyframe_copy(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003f4d0 */
extern void geo_countdown_keyframe_eval(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003f550 */
extern void geo_countdown_object_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003f9a0 */
extern void geo_crx_lut_upload(u32 dest_vaddr, u32 arg1, u32 arg2); /* @rom 0x000037f0 */
extern void geo_draw_frame_entry(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004e90 */
extern void geo_fifo_bootstrap(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004ac0 */
extern void geo_fifo_emit(u32 arg0, u32 arg1); /* @rom 0x0003eca8 */
extern void geo_fifo_matrix_emit(u32 header, u32 pair_count, u32 payload_vaddr); /* @rom 0x00004958 */
extern u32 geo_fifo_preset(u32 arg0, u32 arg1); /* @rom 0x0003ec78 */
extern void geo_fp_lerp3(u32 arg0, void * arg1, void * arg2); /* @rom 0x00003c18 */
extern void geo_lumaram_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004350 */
extern void geo_lumaram_pattern(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004590 */
extern u32 geo_lut_byte_pack(u32 index); /* @rom 0x000037a8 */
extern void geo_mode_setup(u32 arg0, u32 arg1); /* @rom 0x00004708 */
extern void geo_palette_fade_commit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000330a0 */
extern void geo_palette_fade_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00033038 */
extern void geo_palette_irq_frame(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00033180 */
extern void geo_palette_lut_upload(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00003c80 */
extern void geo_palette_mode0_promote(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00033864 */
extern void geo_palette_mode2_stage(u32 from_mode1, u32 arg1, u32 arg2); /* @rom 0x000331d8 */
extern void geo_palette_mode4_fade(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000335b4 */
extern void geo_palette_mode5_colorbase(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00033744 */
extern void geo_palette_mode6_commit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000332d0 */
extern u32 geo_prg_object_opcode_prep(u32 half_arg); /* @rom 0x0003ee98 */
extern void geo_reg_bootstrap(void * arg0, u32 arg1); /* @rom 0x00004658 */
extern void geo_reg_flip_wait(u32 base_vaddr, u32 arg1, u32 arg2); /* @rom 0x00003ba0 */
extern void geo_reg_texture_sync(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000476f0 */
extern void geo_render_state_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000478d0 */
extern void geo_renderer_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00003720 */
extern void geo_rng_next(void); /* @rom 0x00033dc8 */
extern u32 geo_rng_u8(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0005cce8 */
extern u32 geo_scene_glyph_pair(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00005cc0 */
extern void geo_scene_mode_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00005830 */
extern void geo_scene_palette_gate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000058f0 */
extern void geo_scene_row_print(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00005c50 */
extern u32 geo_scene_string_prep(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00005e30 */
extern void geo_submode_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004dd0 */
extern void geo_texture_addr_write(u32 src_vaddr, u32 block_index, u32 block_count); /* @rom 0x000048e8 */
extern u32 geo_view_angle_frac(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003aae8 */
extern void geo_view_boot_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00002920 */
extern u32 geo_view_control_byte_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003b128 */
extern void geo_view_control_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003a280 */
extern void geo_view_copro_vec_push(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00037200 */
extern u32 geo_view_float_clamp(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00027b28 */
extern u32 geo_view_fov_scale(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000395d8 */
extern void geo_view_frame_update(void * arg0, void * arg1, void * arg2); /* @rom 0x00037870 */
extern u32 geo_view_input_gate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000388d0 */
extern void geo_view_latch_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00038680 */
extern void geo_view_matrix_dir_emit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00029120 */
extern void geo_view_matrix_mode_gate(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003ae50 */
extern u32 geo_view_matrix_prep(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003a320 */
extern void geo_view_matrix_row_swap_upload(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00033a50 */
extern void geo_view_matrix_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039690 */
extern void geo_view_matrix_slot_fill(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003ac50 */
extern u32 geo_view_matrix_slot_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003b008 */
extern u32 geo_view_matrix_slot_step(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003af58 */
extern void geo_view_mode_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039c40 */
extern void geo_view_mode_latch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00034ce0 */
extern void geo_view_object_bind(void *arg0, u32 arg1, u32 arg2); /* @rom 0x00033e90 */
extern void geo_view_params(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039540 */
extern void geo_view_pitch_blend(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0003aa38 */
extern void geo_view_pitch_clamp(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039af0 */
extern u32 geo_view_pitch_smooth(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039a90 */
extern void geo_view_scene_apply(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039750 */
extern void geo_view_scene_epilogue(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00034078 */
extern void geo_view_scene_frame(void * arg0, void * arg1, void * arg2); /* @rom 0x00034f40 */
extern void *geo_view_scene_prep(void *arg0, void *arg1, void *arg2); /* @rom 0x00034380 */
extern u32 geo_view_sin_mix(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00038a18 */
extern u32 geo_view_slot_word_pack(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002b0b0 */
extern u32 geo_view_slot_word_probe(u32 arg0, u32 arg1, void *arg2); /* @rom 0x0002aed0 */
extern u32 geo_view_sqrt_mix_a(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00038958 */
extern u32 geo_view_sqrt_mix_b(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000389b8 */
extern void geo_view_table_index_a(void *arg0, u32 arg1, void *arg2); /* @rom 0x0002abc0 */
extern void geo_view_table_index_b(void *arg0, void *arg1, u32 arg2); /* @rom 0x0002acc0 */
extern void geo_view_table_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000377e0 */
extern u32 geo_view_trig_scale(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00039b80 */
extern void geo_vsync_wait(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00004758 */
extern void geo_workram_pose_ring_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000460e8 */
extern void geo_workram_slot_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00046098 */
extern void irq_dispatcher(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000018d8 */
extern void irq_enable_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001780 */
extern void irq_init_major(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001490 */
extern void irq_mask_helper(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001560 */
extern void irq_timer0_latch(u32 arg0, u32 arg1); /* @rom 0x00025c68 */
extern void irq_timer_arm(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00001650 */
extern void libc_memcpy(void * dst, const void * src, u32 len); /* @rom 0x0005daa0 */
extern void libc_printf(const char * fmt, u32 arg1, u32 arg2); /* @rom 0x0005cec0 */
extern void *libc_printf_dispatch(void * arg0, u32 arg1, u32 arg2); /* @rom 0x0005cf50 */
extern void libc_printf_format_loop(void); /* @rom 0x0005cfb8 */
extern void *libc_scanf_setup(void * arg0, void * arg1, u32 arg2); /* @rom 0x0005ce18 */
extern void *libc_strcpy(void * dst, const void * src); /* @rom 0x0005cdc8 */
extern void maincpu_reset_entry(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00000420 */
extern void palram_batch_upload(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a200 */
extern void palram_bus_merge_host(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0002a4e0 */
extern void palram_colorbase_upload(u32 slot, u32 merge_index, u32 arg2); /* @rom 0x00026918 */
extern void palram_geo_colorbase_refresh(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000333c8 */
extern void *placement_geo_feeder(void * arg0, void * arg1, u32 arg2); /* @rom 0x00023cc8 */
extern u32 post_reset_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00000570 */
extern void scene_list_seed(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00029a68 */
extern u32 scene_lookup_fn(u32 table_index, u32 mask_src); /* @rom 0x00014788 */
extern void scene_setup_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00012d00 */
extern u32 scene_stream_lookup(u32 index, u32 base); /* @rom 0x00029ae8 */
extern void scene_view_scale(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00026fd8 */
extern void sound_comm_init(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00025ce0 */
extern void sound_uart_finish(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00025bf8 */
extern void sound_uart_toggle(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00025bc0 */
extern u32 test_menu_backup(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00007910 */
extern u32 test_menu_bookkeeping(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000a3d0 */
extern u32 test_menu_coin(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000be30 */
extern u32 test_menu_crt(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00006a20 */
extern u32 test_menu_drive(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00007d80 */
extern u32 test_menu_exit(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00007fd0 */
extern u32 test_menu_game_assign(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00006f80 */
extern u32 test_menu_input(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00006400 */
extern void test_menu_input_draw(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000061e0 */
extern u32 test_menu_memory(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00008840 */
extern u32 test_menu_output(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00007670 */
extern u32 test_menu_sound(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00008b00 */
extern void texture_bank_select(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x00003940 */
extern void tile_attract_angle_fixup(u32 arg0, u32 arg1); /* @rom 0x00027bd8 */
extern void tile_attract_mode_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000cc70 */
extern void tile_attract_palram_gate(u32 color_word); /* @rom 0x000272b0 */
extern void tile_attract_phase_comm(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000c5d0 */
extern void tile_attract_phase_finalize(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000cbf0 */
extern void tile_attract_phase_network(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000c840 */
extern void tile_attract_phase_node(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000c990 */
extern void tile_attract_phase_pair(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x005abb30 */
extern void tile_attract_phase_slave(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000c750 */
extern void tile_attract_string_draw(void * arg0, u32 arg1, u32 arg2); /* @rom 0x00028990 */
extern void tile_attract_text_dispatch(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x0000c640 */
extern void tile_char_upload(u32 arg0, u32 arg1, u32 arg2, u32 arg3, u32 arg4); /* @rom 0x00026b90 */
extern void tile_char_upload_fb(u32 arg0, u32 arg1, u32 arg2, u32 arg3, u32 arg4); /* @rom 0x00026c40 */
extern void tile_cursor_seed(u32 x, u32 y); /* @rom 0x00026e18 */
extern void tile_map_bank_clear(u32 map_base); /* @rom 0x00026b60 */
extern void tile_map_banks_clear(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000269d0 */
extern void tile_map_banks_clear_odd(u32 arg0, u32 arg1, u32 arg2); /* @rom 0x000269f0 */
extern void tile_texture_descriptor_apply(u32 slot_index, u32 fill_byte, u32 arg2); /* @rom 0x000261b0 */

#endif
