/* Auto-generated by tools/decomp/gen_lift_main.py — do not edit. */
/* Regenerate: make lift-main */

#include <stdio.h>
#include <stdlib.h>

#include "i960_host.h"
#include "i960_lift.h"
#include "track_viewer.h"

/* Entry: boot_entry (cold boot dispatch @ 0x310 (PRCB path → maincpu_reset_entry)) */
int main(int argc, char **argv)
{
    track_viewer_opts_t viewer_opts;
    int viewer_mode;

    i960_host_load_rom();
    i960_host_reset();

    viewer_mode = track_viewer_cli_parse(argc, argv, &viewer_opts);
    if (viewer_mode == 2)
        return 0;
    if (viewer_mode < 0)
        return 1;
    if (viewer_mode == 1) {
        i960_host_trace_init();
        if (viewer_opts.geo_fifo_path)
            return i960_lift_geo_fifo_decode_run(&viewer_opts);
        if (viewer_opts.cgm_decode)
            return i960_lift_cgm_decode_run(&viewer_opts);
        if (viewer_opts.viewer_boot)
            return i960_lift_boot_screen_run(&viewer_opts);
        return i960_lift_track_viewer_run(&viewer_opts);
    }

    i960_host_trace_init();

    /* cold boot @ 0x310 — boot_entry_host skips HW timer @ fp+0x40 */
    boot_entry_host(0, 0, 0);

    /* vector @ ROM 0x3DC → post_reset_dispatch @ 0x570 (callx main engine) */
    i960_host_run_post_reset(0, 0, 0);

    i960_host_trace_summary();

    return (int)g0;
}
